services:
  - type: web
    name: mongoUse
    env: node
    buildCommand: "cd MongoUse && npm install"
    startCommand: "cd MongoUse && npm start"
    branch: master
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8080"

  # PR Previews (automatically handled by Render)
  - type: web
    name: mongoUse-pr-preview
    env: node
    buildCommand: "cd MongoUse && npm install"
    startCommand: "cd MongoUse && npm start"
    branch: pr
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8080"

